In [288]:
import csv
import numpy as np
import pandas as pd

In [289]:
pit_april = pd.read_csv("pit_batting_march_april.csv")
pit_may = pd.read_csv("pit_batting_may.csv")

In [290]:
pit_april

,Players,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,HBP,SF,TB,AVG,OBP,SLG,OPS
0,Josh Bell,27.0,98.0,16.0,28.0,8.0,2.0,6.0,21.0,12.0,27.0,0.0,1.0,1.0,2.0,58.0,0.286,0.363,0.592,0.955
1,Melky Cabrera,26.0,85.0,8.0,28.0,5.0,0.0,3.0,7.0,3.0,11.0,1.0,0.0,0.0,0.0,42.0,0.329,0.352,0.494,0.846
2,JB Shuck,25.0,46.0,3.0,9.0,0.0,1.0,0.0,2.0,8.0,10.0,1.0,1.0,1.0,0.0,11.0,0.196,0.327,0.239,0.566
3,Colin Moran,25.0,56.0,5.0,15.0,3.0,0.0,2.0,11.0,7.0,12.0,0.0,0.0,0.0,0.0,24.0,0.268,0.349,0.429,0.778
4,Francisco Cervelli,24.0,80.0,9.0,14.0,2.0,0.0,1.0,4.0,6.0,24.0,0.0,0.0,1.0,0.0,19.0,0.175,0.241,0.238,0.479
5,Adam Frazier,24.0,93.0,13.0,24.0,5.0,0.0,1.0,6.0,10.0,15.0,2.0,1.0,1.0,0.0,32.0,0.258,0.337,0.344,0.681
6,Jung Ho Kang,24.0,75.0,5.0,12.0,3.0,0.0,4.0,8.0,6.0,28.0,0.0,0.0,0.0,0.0,27.0,0.160,0.222,0.360,0.582
7,Pablo Reyes,22.0,36.0,5.0,5.0,0.0,0.0,0.0,3.0,3.0,14.0,0.0,0.0,0.0,0.0,5.0,0.139,0.205,0.139,0.344
8,Jason Martin,17.0,35.0,3.0,8.0,2.0,0.0,0.0,2.0,3.0,10.0,2.0,0.0,0.0,0.0,10.0,0.229,0.289,0.286,0.575
9,Starling Marte,17.0,75.0,9.0,15.0,4.0,1.0,3.0,11.0,2.0,16.0,3.0,1.0,2.0,0.0,30.0,0.200,0.241,0.400,0.641
10,Erik Gonzalez,16.0,51.0,2.0,11.0,2.0,1.0,0.0,2.0,6.0,13.0,3.0,0.0,0.0,0.0,14.0,0.216,0.298,0.275,0.573
11,Cole Tucker,10.0,36.0,4.0,9.0,3.0,0.0,1.0,2.0,2.0,12.0,0.0,0.0,0.0,0.0,15.0,0.250,0.289,0.417,0.706
12,Bryan Reynolds,8.0,26.0,2.0,11.0,5.0,0.0,1.0,1.0,0.0,6.0,0.0,0.0,0.0,0.0,19.0,0.423,0.423,0.731,1.154
13,Gregory Polanco,7.0,26.0,2.0,7.0,1.0,0.0,0.0,0.0,3.0,6.0,0.0,0.0,0.0,0.0,8.0,0.269,0.345,0.308,0.653
14,Elias Diaz,5.0,16.0,1.0,2.0,1.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,3.0,0.125,0.125,0.188,0.313
15,Kevin Newman,6.0,11.0,0.0,3.0,1.0,0.0,0.0,2.0,1.0,3.0,0.0,0.0,0.0,0.0,4.0,0.273,0.333,0.364,0.697
16,Jason Stallings,4.0,11.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,3.0,0.273,0.273,0.273,0.545
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [291]:
pit_april.drop(17, axis=0, inplace=True)
pit_april.drop(18, axis=0, inplace=True)
pit_april.drop(19, axis=0, inplace=True)
pit_april.drop(20, axis=0, inplace=True)
pit_april.drop(21, axis=0, inplace=True)
pit_april.drop(22, axis=0, inplace=True)
pit_april.drop(23, axis=0, inplace=True)
pit_april.drop(24, axis=0, inplace=True)
pit_april.drop(25, axis=0, inplace=True)
pit_april.drop(26, axis=0, inplace=True)
pit_april.drop(27, axis=0, inplace=True)
pit_april.drop(28, axis=0, inplace=True)
pit_april.drop(29, axis=0, inplace=True)
pit_april.drop(30, axis=0, inplace=True)
pit_april.drop(31, axis=0, inplace=True)
pit_april.drop(32, axis=0, inplace=True)
pit_april.drop(33, axis=0, inplace=True)
pit_april.drop(34, axis=0, inplace=True)
pit_april.drop(35, axis=0, inplace=True)
pit_april.drop(36, axis=0, inplace=True)
pit_april.drop(37, axis=0, inplace=True)
pit_april.drop(38, axis=0, inplace=True)
pit_april.drop(39, axis=0, inplace=True)
pit_april.drop(40, axis=0, inplace=True)
pit_april.drop(41, axis=0, inplace=True)

In [292]:
players_april = ['Bell, Josh', 'Cabrera, Melky', 'Shuck, JB', 'Moran, Colin', 'Cervelli, Francisco', 'Frazier, Adam', 'Kang, Jung Ho', 'Reyes, Pablo', 'Martin, Jason', 'Marte, Starling', 'Gonzalez, Erik', 'Tucker, Cole', 'Reynolds, Bryan', 'Polanco, Gregory', 'Diaz, Elias', 'Newman, Kevin', 'Stallings, Jason']

In [293]:
del pit_april['Players']
del pit_april['HBP']
del pit_april['SF']
del pit_april['TB']

In [294]:
pit_april.index = players_april

In [295]:
pit_april

,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,AVG,OBP,SLG,OPS
"Bell, Josh",27.0,98.0,16.0,28.0,8.0,2.0,6.0,21.0,12.0,27.0,0.0,1.0,0.286,0.363,0.592,0.955
"Cabrera, Melky",26.0,85.0,8.0,28.0,5.0,0.0,3.0,7.0,3.0,11.0,1.0,0.0,0.329,0.352,0.494,0.846
"Shuck, JB",25.0,46.0,3.0,9.0,0.0,1.0,0.0,2.0,8.0,10.0,1.0,1.0,0.196,0.327,0.239,0.566
"Moran, Colin",25.0,56.0,5.0,15.0,3.0,0.0,2.0,11.0,7.0,12.0,0.0,0.0,0.268,0.349,0.429,0.778
"Cervelli, Francisco",24.0,80.0,9.0,14.0,2.0,0.0,1.0,4.0,6.0,24.0,0.0,0.0,0.175,0.241,0.238,0.479
"Frazier, Adam",24.0,93.0,13.0,24.0,5.0,0.0,1.0,6.0,10.0,15.0,2.0,1.0,0.258,0.337,0.344,0.681
"Kang, Jung Ho",24.0,75.0,5.0,12.0,3.0,0.0,4.0,8.0,6.0,28.0,0.0,0.0,0.160,0.222,0.360,0.582
"Reyes, Pablo",22.0,36.0,5.0,5.0,0.0,0.0,0.0,3.0,3.0,14.0,0.0,0.0,0.139,0.205,0.139,0.344
"Martin, Jason",17.0,35.0,3.0,8.0,2.0,0.0,0.0,2.0,3.0,10.0,2.0,0.0,0.229,0.289,0.286,0.575
"Marte, Starling",17.0,75.0,9.0,15.0,4.0,1.0,3.0,11.0,2.0,16.0,3.0,1.0,0.200,0.241,0.400,0.641
"Gonzalez, Erik",16.0,51.0,2.0,11.0,2.0,1.0,0.0,2.0,6.0,13.0,3.0,0.0,0.216,0.298,0.275,0.573
"Tucker, Cole",10.0,36.0,4.0,9.0,3.0,0.0,1.0,2.0,2.0,12.0,0.0,0.0,0.250,0.289,0.417,0.706
"Reynolds, Bryan",8.0,26.0,2.0,11.0,5.0,0.0,1.0,1.0,0.0,6.0,0.0,0.0,0.423,0.423,0.731,1.154
"Polanco, Gregory",7.0,26.0,2.0,7.0,1.0,0.0,0.0,0.0,3.0,6.0,0.0,0.0,0.269,0.345,0.308,0.653
"Diaz, Elias",5.0,16.0,1.0,2.0,1.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,0.125,0.125,0.188,0.313
"Newman, Kevin",6.0,11.0,0.0,3.0,1.0,0.0,0.0,2.0,1.0,3.0,0.0,0.0,0.273,0.333,0.364,0.697
"Stallings, Jason",4.0,11.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.273,0.273,0.273,0.545

In [296]:
april_totals = pit_april.sum(axis=0)

In [297]:
april_totals[2]

88.0

In [298]:
april_games = 27
april_runs = round(april_totals[2])
april_hits = round(april_totals[3])
april_2b = round(april_totals[4])
april_3b = round(april_totals[5])
april_hr = round(april_totals[6])
april_rbi = round(april_totals[7])
april_bb = round(april_totals[8])
april_so = round(april_totals[9])
april_sb = round(april_totals[10])
april_cs = round(april_totals[11])
april_avg = round(april_totals[12]/17, 3)
april_obp = round(april_totals[13]/17, 3)
april_slg = round(april_totals[14]/17, 3)
april_ops = round(april_totals[15]/17, 3)

In [299]:
pit_may

,Players,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,AVG,OBP,SLG,OPS
0,Josh Bell,21.0,83.0,19.0,33.0,8.0,0.0,10.0,26.0,9.0,18.0,0.0,0.0,0.398,0.457,0.855,1.312
1,Starling Marte,21.0,91.0,17.0,26.0,6.0,1.0,2.0,8.0,2.0,16.0,5.0,0.0,0.286,0.323,0.440,0.762
2,Adam Frazier,20.0,85.0,11.0,21.0,4.0,1.0,1.0,6.0,2.0,10.0,0.0,1.0,0.247,0.273,0.353,0.626
3,Colin Moran,20.0,61.0,4.0,15.0,3.0,0.0,2.0,11.0,4.0,20.0,0.0,0.0,0.246,0.288,0.393,0.681
4,Bryan Reynolds,20.0,59.0,8.0,16.0,3.0,0.0,3.0,11.0,8.0,13.0,0.0,0.0,0.271,0.358,0.475,0.833
5,Melky Cabrera,19.0,53.0,6.0,18.0,4.0,0.0,0.0,8.0,5.0,5.0,1.0,0.0,0.340,0.397,0.415,0.812
6,Gregory Polanco,17.0,68.0,14.0,18.0,4.0,1.0,5.0,13.0,5.0,15.0,0.0,1.0,0.265,0.324,0.574,0.898
7,Cole Tucker,17.0,48.0,4.0,4.0,0.0,0.0,1.0,3.0,3.0,16.0,0.0,0.0,0.083,0.137,0.146,0.283
8,Kevin Newman,16.0,44.0,5.0,16.0,4.0,1.0,0.0,4.0,5.0,10.0,1.0,0.0,0.364,0.440,0.500,0.940
9,Elias Diaz,15.0,49.0,6.0,14.0,0.0,0.0,0.0,3.0,3.0,9.0,0.0,0.0,0.286,0.327,0.286,0.613
10,Francisco Cervelli,9.0,28.0,2.0,6.0,1.0,0.0,0.0,1.0,3.0,7.0,1.0,0.0,0.214,0.333,0.250,0.583
11,Jung Ho Kang,7.0,15.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,0.0,0.0,0.000,0.118,0.000,0.118
12,Jake Elmore,10.0,18.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.056,0.056,0.056,0.111
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [300]:
pit_may.drop(13, axis=0, inplace=True)
pit_may.drop(14, axis=0, inplace=True)

In [301]:
pit_may.drop(15, axis=0, inplace=True)

In [302]:
players_may = ['Bell, Josh', 'Marte, Starling', 'Frazier, Adam', 'Moran, Colin', 'Reynolds, Bryan', 'Cabrera, Melky', 'Polanco, Gregory', 'Tucker, Cole', 'Newman, Kevin', 'Diaz, Elias', 'Cervelli, Francisco', 'Kang, Jung Ho', 'Elmore, Jake']

In [303]:
pit_may.index = players_may

In [304]:
del pit_may['Players']

In [305]:
pit_may

,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,AVG,OBP,SLG,OPS
"Bell, Josh",21.0,83.0,19.0,33.0,8.0,0.0,10.0,26.0,9.0,18.0,0.0,0.0,0.398,0.457,0.855,1.312
"Marte, Starling",21.0,91.0,17.0,26.0,6.0,1.0,2.0,8.0,2.0,16.0,5.0,0.0,0.286,0.323,0.440,0.762
"Frazier, Adam",20.0,85.0,11.0,21.0,4.0,1.0,1.0,6.0,2.0,10.0,0.0,1.0,0.247,0.273,0.353,0.626
"Moran, Colin",20.0,61.0,4.0,15.0,3.0,0.0,2.0,11.0,4.0,20.0,0.0,0.0,0.246,0.288,0.393,0.681
"Reynolds, Bryan",20.0,59.0,8.0,16.0,3.0,0.0,3.0,11.0,8.0,13.0,0.0,0.0,0.271,0.358,0.475,0.833
"Cabrera, Melky",19.0,53.0,6.0,18.0,4.0,0.0,0.0,8.0,5.0,5.0,1.0,0.0,0.340,0.397,0.415,0.812
"Polanco, Gregory",17.0,68.0,14.0,18.0,4.0,1.0,5.0,13.0,5.0,15.0,0.0,1.0,0.265,0.324,0.574,0.898
"Tucker, Cole",17.0,48.0,4.0,4.0,0.0,0.0,1.0,3.0,3.0,16.0,0.0,0.0,0.083,0.137,0.146,0.283
"Newman, Kevin",16.0,44.0,5.0,16.0,4.0,1.0,0.0,4.0,5.0,10.0,1.0,0.0,0.364,0.440,0.500,0.940
"Diaz, Elias",15.0,49.0,6.0,14.0,0.0,0.0,0.0,3.0,3.0,9.0,0.0,0.0,0.286,0.327,0.286,0.613
"Cervelli, Francisco",9.0,28.0,2.0,6.0,1.0,0.0,0.0,1.0,3.0,7.0,1.0,0.0,0.214,0.333,0.250,0.583
"Kang, Jung Ho",7.0,15.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,0.0,0.0,0.000,0.118,0.000,0.118
"Elmore, Jake",10.0,18.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.056,0.056,0.056,0.111

In [306]:
may_totals = pit_may.sum(axis=0)

In [307]:
may_games = 21
may_runs = round(may_totals[2])
may_hits = round(may_totals[3])
may_2b = round(may_totals[4])
may_3b = round(may_totals[5])
may_hr = round(may_totals[6])
may_rbi = round(may_totals[7])
may_bb = round(may_totals[8])
may_so = round(may_totals[9])
may_sb = round(may_totals[10])
may_cs = round(may_totals[11])
may_avg = round(may_totals[12]/17, 4)
may_obp = round(may_totals[13]/17, 3)
may_slg = round(may_totals[14]/17, 3)
may_ops = round(may_totals[15]/17, 3)

In [308]:
total_games = april_games + may_games
total_runs = april_runs + may_runs
total_hits = april_hits + may_hits
total_2b = april_2b + may_2b
total_3b = april_3b + may_3b
total_hr = april_hr + may_hr
total_rbi = april_rbi + may_rbi
total_bb = april_bb + may_bb
total_so = april_so + may_so
total_sb = april_sb + may_sb
total_cs = april_cs + may_cs
total_avg = (april_avg + may_avg)/2
total_obp = (april_obp + may_obp)/2
total_slg = (april_slg + may_slg)/2
total_ops = (april_ops + may_ops)/2

In [309]:
teamStats = pd.DataFrame({'G': [april_games, may_games, total_games], 'R': [april_runs, may_runs, total_runs], 'H': [april_hits, may_hits, total_hits], '2B': [april_2b, may_2b, total_2b], '3B': [april_3b, may_3b, total_3b], 'HR': [april_hr, may_hr, total_hr], 'RBI': [april_rbi, may_rbi, total_rbi], 'BB': [april_bb, may_bb, total_bb], 'SO': [april_so, may_so, total_so], 'SB': [april_sb, may_sb, total_sb], 'CS': [april_cs, may_cs, total_cs], 'AVG': [april_avg, may_avg, total_avg], 'OBP': [april_obp, may_obp, total_obp], 'SLG': [april_slg, may_slg, total_slg], 'OPS': [april_ops, may_ops, total_ops]})
teamStats.index = ['March/April', 'May', 'Totals']

In [310]:
teamStats

,G,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,AVG,OBP,SLG,OPS
March/April,27,88.0,204.0,45.0,5.0,22.0,83.0,72.0,212.0,12.0,4.0,0.2390,0.295,0.357,0.652
May,21,97.0,188.0,37.0,4.0,24.0,94.0,51.0,145.0,8.0,2.0,0.1798,0.225,0.279,0.504
Totals,48,185.0,392.0,82.0,9.0,46.0,177.0,123.0,357.0,20.0,6.0,0.2094,0.260,0.318,0.578